# Generated by Django 6.0.2 on 2026-02-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='room_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('2 star', '2 star'), ('5 star', '5 star'), ('delux', 'delux')], default='Normal', max_length=100),
        ),
    ]
