# Generated by Django 6.0.2 on 2026-02-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Price',
            new_name='price',
        ),
    ]
