# Generated by Django 6.0.2 on 2026-02-26 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_rename_price_room_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Normal', 'Normal'), ('2 star', '2 star'), ('5 star', '5 star'), ('delux', 'delux')], max_length=100)),
                ('count', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookingapp.hotelbooking')),
            ],
        ),
    ]
