# Generated by Django 6.0.2 on 2026-02-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
