# Generated by Django 6.0.2 on 2026-02-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_bookingitem'),
        ('bookingapp', '0005_alter_hotelbooking_hotel_alter_room_available_rooms_and_more'),
    ]

    operations = [
    ]
