# Generated by Django 6.0.2 on 2026-02-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0006_merge_20260226_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingItem',
        ),
    ]
