# Generated by Django 6.0.2 on 2026-02-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_delete_bookingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='rooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.room'),
        ),
    ]
