# Generated by Django 6.0.2 on 2026-02-26 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_hotelbooking_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='available_room',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenumber',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
