# Generated by Django 6.0.2 on 2026-02-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0009_hotelbooking_available_room_alter_user_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='available_room',
        ),
    ]
