# Generated by Django 6.0.2 on 2026-02-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0012_hotelbooking_total_amount_alter_hotel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='password',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
