# Generated by Django 6.0.2 on 2026-03-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingapp.user'),
        ),
    ]
