# Generated by Django 6.0.2 on 2026-03-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0016_hotelbooking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
