# Generated by Django 6.0.2 on 2026-03-02 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_alter_hotelbooking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingapp.user'),
        ),
    ]
